package.json
I fixed the problem of dependency missing in react project.
closes #92 
Changed styled-component depencency from 'devDependencies' to 'dependencies"
To create a new project with beagle-react  it is no longer necessary to add styled-components manually
Fixed the problem of styled-components dependency missing.
=> Fixing dependency error

package.json
=> releases 1.1.0

.github/workflows/publish.yml, .gitignore
Change publish action to run cache clean.
Change publish action to run cache clean.
On PR to master must run cache clean.
Change publish action to run cache clean.
=> change publish action

.github/workflows/validate.yml
Corrigi a action de validação de PR para usar a master do beagle-web-core ao invés do npm.
Mudei a action `validate`
Basta ver o check de validação deste PR
Corrige a action de validação de PR para usar a master do beagle-web-core ao invés do npm
=> Validação de PR com a master do beagle-web-core

src/component.tsx, src/components/BeagleButton/index.tsx, src/components/BeagleContainer/index.tsx, src/components/BeagleFutureListView/index.tsx, src/components/BeagleImage/index.tsx, src/components/BeagleTabBar/index.tsx, src/components/BeagleTabView/BeagleTabItem/index.tsx, src/components/BeagleTouchable/index.tsx, src/renderer.ts, src/types.ts, src/utils/beagleComponent.ts
Adapts beagle-react to work with the new structure of beagle-web-core.
Updated imports and some services usage.
I ran this version of the lib for both Beagle Forms and Beagle Playground (every demo example + global context).
Adapts beagle-react to work with the new structure of beagle-web-core.
=> Updates beagle-react according to the new core structure

.eslintrc.js, package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json, packages/beagle-react/src/components/BeagleButton/index.tsx, packages/beagle-react/src/components/BeagleButton/styled.ts, packages/beagle-react/src/components/BeagleContainer/index.tsx, packages/beagle-react/src/components/BeagleContainer/styled.ts, packages/beagle-react/src/components/BeagleFutureListView/index.tsx, packages/beagle-react/src/components/BeagleFutureListView/scroll.ts, packages/beagle-react/src/components/BeagleFutureListView/styled.ts, packages/beagle-react/src/components/BeagleFutureListView/types.ts, packages/beagle-react/src/components/BeagleLazy/index.tsx, packages/beagle-react/src/components/BeagleTabView/BeagleTabItem/index.tsx, packages/common/renderer.ts, packages/common/types.ts
Combines the following 3 PR's into one: #126 #128 #129 
Closing #130 
- BeagleContext is now ViewContentmanager
- Concludes the listview implementation
- Adds the "disabled" attribute to the button
- Fixes some styling issues with the container
=> ListView and ViewContentManager

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
=> releases v1.2.0

.github/workflows/publish.yml
Fixed script to publish version in NPM
Added ```yarn``` prefix before lerna command
Check publish.yml script
=> Update script publish.yml

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
=> pre-release 1.3.0 rc1

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
=> releases 1.3.0

packages/beagle-react/src/components/BeagleText/styled.ts
Add the style white-space: pre to the paragraph.
Add white-space: pre in styled
Creating a text component and adding line breaks and tabs
closes: ZupIT/beagle-web-core#274
=> fix text-component

.github/workflows/validate.yml
commenting only if the secret is available
=> Trying to fix external PRs

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
=> release v1.4.0

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
Releases 1.5.0-rc.1 (pre-release)
Check it out in Playground Beta: http://playground-beta.usebeagle.io/
=> Releases 1.5.0-rc.1 (pre-release)

packages/beagle-react-native/package.json, packages/beagle-react-native/src/index.ts, packages/common/types.ts
Fixed the type-check for reactive that was crashing the CI/CD build
Added types of react-native to the project and passed the right type to Beagle config
Type-check step should run perfectly
=> fix type-check

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
=> Releases v1.6.0

packages/common/types.ts, packages/common/useComponent.ts
Updated interface according to the PR https://github.com/ZupIT/beagle-web-core/pull/327
Deprecated old properties and treated new ones
Create a project and pass a RemoteView object in the route parameter of BeagleRemoveView
=> Updates interface

package.json, packages/beagle-react-native/package.json, packages/beagle-react/package.json
Releases 1.7.0
Attention: GitHub is crazy, I changed nothing but the versions. `151 additions and 151 deletions` is a false statement.
=> Releases 1.7.0

package.json, packages/beagle-react/package.json
=> releases v1.9.0

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/publish.yml, .github/workflows/validate.yml, CONTRIBUTING.md, README.md, packages/beagle-react/README.md
Renamed branch master to main on github actions
Link to the issue https://github.com/ZupIT/beagle/issues/1577
=> feat: Rename master to main

.gitattributes, packages/beagle-react/src/components/BeagleDynamicLists/DynamicListCore/index.tsx
Improved the logic of `componentManager` for lists and add EOL config for git
=> Fix: List componentManager improvements and git eol

packages/beagle-react/README.md
closes #221
Updated the README file for react.js module
=> Updates README file for react

CONTRIBUTING.md, README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
Added a new README pattern to the repository.
**- Description for the changelog** Updated Readme.
=> Updated Readme

SECURITY.md
=> Adds security policy

.github/dependabot.yml
=> Updates dependabot interval

.github/workflows/horusec.yml
Removed unnecessary workflow secret
=> removes unused secrets

.github/dependabot.yml, .github/workflows/horusec.yml, horusec-config.json
- Added false positive to horusec file and updated version
=> Updates horusec files

.github/workflows/auto-comment.yml
- Added auto comment action for newly opened Pull Requests and Issues
=> Adds auto comment action

horusec-config.json, src/components/BeagleButton/index.tsx
Fixed button text now when an object is passed it is displayed in string
Story ID: 217157
Related story: https://app.shortcut.com/orange-stack/story/217157/buttons-don-t-work-with-wild-types-of-texts-on-beagle-react?stories_sort_by=priority&stories_group_by=WORKFLOW_STATE
=> Fix: button text

.github/workflows/header.license-checker.yml
Updated action for license header checking
=> Updates action for header checking

.github/workflows/horusec.yml
Added Horusec token for web manager
=> Adds web token for horusec

SECURITY.md
Updates security file with new e-mail
=> Updates security file

package.json
Signed-off-by: Arthur Bleil <arthur.bleil@zup.com.br>
=> update: core version
